package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

type generator struct {
	types      map[string]*ast.StructType
	collector  bytes.Buffer
	applier    bytes.Buffer
	relationID int
	loopID     int
}

func main() {
	typeName := flag.String("type", "", "root struct type")
	output := flag.String("output", "molding.gen.go", "generated file")
	flag.Parse()
	if *typeName == "" {
		fail(errorsf("-type is required"))
	}

	packageName, types, err := loadPackage(*output)
	if err != nil {
		fail(err)
	}
	root, exists := types[*typeName]
	if !exists {
		fail(errorsf("type %s was not found", *typeName))
	}
	g := &generator{types: types}
	g.collector.WriteString("\tif value == nil {\n\t\treturn nil\n\t}\n")
	g.collector.WriteString("\treferenceIDs := make([]string, 0)\n\tseen := make(map[string]struct{})\n")
	g.applier.WriteString("\tif value == nil {\n\t\treturn\n\t}\n")
	if err := g.walkStruct(root, "value", map[string]bool{*typeName: true}); err != nil {
		fail(err)
	}
	g.collector.WriteString("\treturn referenceIDs\n")

	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by molding; DO NOT EDIT.\n\npackage %s\n\n", packageName)
	fmt.Fprintf(&source, "func (value *%s) RefIDs(kind string) []string {\n%s}\n\n", *typeName, g.collector.String())
	fmt.Fprintf(&source, "func (value *%s) ApplyRefs(kind string, references map[string]string) {\n%s}\n", *typeName, g.applier.String())
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fail(fmt.Errorf("format generated source: %w\n%s", err, source.String()))
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fail(fmt.Errorf("write %s: %w", *output, err))
	}
}

func loadPackage(output string) (string, map[string]*ast.StructType, error) {
	entries, err := os.ReadDir(".")
	if err != nil {
		return "", nil, err
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == filepath.Base(output) {
			continue
		}
		files = append(files, name)
	}
	sort.Strings(files)
	if len(files) == 0 {
		return "", nil, errorsf("no Go source files found")
	}

	fileSet := token.NewFileSet()
	types := make(map[string]*ast.StructType)
	packageName := ""
	for _, name := range files {
		file, parseErr := parser.ParseFile(fileSet, name, nil, 0)
		if parseErr != nil {
			return "", nil, parseErr
		}
		if packageName == "" {
			packageName = file.Name.Name
		} else if packageName != file.Name.Name {
			return "", nil, errorsf("multiple packages found")
		}
		for _, declaration := range file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, specification := range general.Specs {
				typeSpec := specification.(*ast.TypeSpec)
				if structure, ok := typeSpec.Type.(*ast.StructType); ok {
					types[typeSpec.Name.Name] = structure
				}
			}
		}
	}
	return packageName, types, nil
}

func (g *generator) walkStruct(structure *ast.StructType, expression string, stack map[string]bool) error {
	for _, field := range structure.Fields.List {
		if field.Tag == nil || len(field.Names) != 1 {
			continue
		}
		tagText, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return err
		}
		tag, tagged := reflect.StructTag(tagText).Lookup("ref")
		if !tagged {
			continue
		}
		fieldExpression := expression + "." + field.Names[0].Name
		if tag == "inline" {
			if err := g.walkInline(field.Type, fieldExpression, stack); err != nil {
				return fmt.Errorf("%s: %w", field.Names[0].Name, err)
			}
			continue
		}
		kind, destinationName, found := strings.Cut(tag, ":")
		if !found || kind == "" || destinationName == "" {
			return errorsf("%s ref must use kind:Destination syntax", field.Names[0].Name)
		}
		if !isString(field.Type) {
			return errorsf("%s must be a string", field.Names[0].Name)
		}
		destination, ok := namedField(structure, destinationName)
		if !ok || !isString(destination.Type) {
			return errorsf("destination %s must be a string field", destinationName)
		}
		g.emitRelation(kind, fieldExpression, expression+"."+destinationName)
	}
	return nil
}

func (g *generator) walkInline(fieldType ast.Expr, expression string, stack map[string]bool) error {
	switch typed := fieldType.(type) {
	case *ast.ArrayType:
		index := fmt.Sprintf("refIndex%d", g.loopID)
		g.loopID++
		fmt.Fprintf(&g.collector, "\tfor %s := range %s {\n", index, expression)
		fmt.Fprintf(&g.applier, "\tfor %s := range %s {\n", index, expression)
		if err := g.walkInline(typed.Elt, fmt.Sprintf("%s[%s]", expression, index), stack); err != nil {
			return err
		}
		g.collector.WriteString("\t}\n")
		g.applier.WriteString("\t}\n")
		return nil
	case *ast.StarExpr:
		fmt.Fprintf(&g.collector, "\tif %s != nil {\n", expression)
		fmt.Fprintf(&g.applier, "\tif %s != nil {\n", expression)
		if err := g.walkInline(typed.X, expression, stack); err != nil {
			return err
		}
		g.collector.WriteString("\t}\n")
		g.applier.WriteString("\t}\n")
		return nil
	case *ast.Ident:
		structure, exists := g.types[typed.Name]
		if !exists {
			return errorsf("inline type %s is not a local struct", typed.Name)
		}
		if stack[typed.Name] {
			return errorsf("inline cycle through %s", typed.Name)
		}
		nextStack := make(map[string]bool, len(stack)+1)
		for name, present := range stack {
			nextStack[name] = present
		}
		nextStack[typed.Name] = true
		return g.walkStruct(structure, expression, nextStack)
	default:
		return errorsf("unsupported inline type %T", fieldType)
	}
}

func (g *generator) emitRelation(kind, source, destination string) {
	id := g.relationID
	g.relationID++
	fmt.Fprintf(&g.collector, "\tif kind == %q {\n", kind)
	fmt.Fprintf(&g.collector, "\t\treferenceID%d := %s\n", id, source)
	fmt.Fprintf(&g.collector, "\t\tif referenceID%d != \"\" {\n", id)
	fmt.Fprintf(&g.collector, "\t\t\tif _, exists := seen[referenceID%d]; !exists {\n", id)
	fmt.Fprintf(&g.collector, "\t\t\t\tseen[referenceID%d] = struct{}{}\n", id)
	fmt.Fprintf(&g.collector, "\t\t\t\treferenceIDs = append(referenceIDs, referenceID%d)\n", id)
	g.collector.WriteString("\t\t\t}\n\t\t}\n\t}\n")
	fmt.Fprintf(&g.applier, "\tif kind == %q {\n", kind)
	fmt.Fprintf(&g.applier, "\t\tif reference%d, exists := references[%s]; exists {\n", id, source)
	fmt.Fprintf(&g.applier, "\t\t\t%s = reference%d\n", destination, id)
	g.applier.WriteString("\t\t}\n\t}\n")
}

func namedField(structure *ast.StructType, name string) (*ast.Field, bool) {
	for _, field := range structure.Fields.List {
		if len(field.Names) == 1 && field.Names[0].Name == name {
			return field, true
		}
	}
	return nil, false
}

func isString(expression ast.Expr) bool {
	identifier, ok := expression.(*ast.Ident)
	return ok && identifier.Name == "string"
}

func errorsf(format string, arguments ...any) error {
	return fmt.Errorf("molding: "+format, arguments...)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
